### ISSUE TITLE
proc.sh第46行变量名写错了

### ISSUE THREAD

**Issue by lizheray** [ZoneTong/falcon-scripts#1]
pid=`netstat -anp | grep ":$port " | grep LISTEN| awk '{print $7}' | awk -F"/" '{ print $1 }'|uniq`

$port应为$p

**Comment by ZoneTong** [comment]
> pid=`netstat -anp | grep ":$port " | grep LISTEN| awk '{print $7}' | awk -F"/" '{ print $1 }'|uniq`
> 
> $port应为$p

thanks, 已修正
